<a href="https://colab.research.google.com/github/talhanoor23/Deep-Learning-Experiments/blob/main/Regression/NeuralNetwork_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.1

# **Data_Preprocessing**

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib
import plotly.express as px
import os
%matplotlib inline

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [ ]:
!kaggle datasets download -d yasserh/housing-prices-dataset

Dataset URL: https://www.kaggle.com/datasets/yasserh/housing-prices-dataset
License(s): CC0-1.0
Downloading housing-prices-dataset.zip to /content
  0% 0.00/4.63k [00:00<?, ?B/s]
100% 4.63k/4.63k [00:00<00:00, 9.32MB/s]

In [ ]:
!unzip /content/housing-prices-dataset.zip

Archive:  /content/housing-prices-dataset.zip
  inflating: Housing.csv

In [ ]:
house_df = pd.read_csv('Housing.csv')

In [ ]:
house_df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
house_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
house_df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [ ]:
house_df.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
fig = px.histogram(house_df, x="price", color='basement', marginal='box', hover_data=house_df.columns)
fig.update_layout(title_text='Housing Prices Dataset', bargap=0.1)

In [ ]:
fig = px.histogram(house_df, x="price", color='mainroad', marginal='box', hover_data=house_df.columns)
fig.update_layout(title_text='Housing Prices Dataset', bargap=0.1)

In [ ]:
fig = px.histogram(house_df, x="airconditioning", color='hotwaterheating', marginal='box', hover_data=house_df.columns)
fig.update_layout(title_text='Housing Prices Dataset', bargap=0.1)

In [ ]:
house_df.basement.value_counts()

basement
no     354
yes    191
Name: count, dtype: int64

In [ ]:
house_df.airconditioning.value_counts()

airconditioning
no     373
yes    172
Name: count, dtype: int64

In [ ]:
house_df.bedrooms.value_counts()

bedrooms
3    300
2    136
4     95
5     10
6      2
1      2
Name: count, dtype: int64

In [ ]:
house_df.stories.value_counts()

stories
2    238
1    227
4     41
3     39
Name: count, dtype: int64

In [ ]:
fig = px.scatter(house_df, x="price", y="area", color='airconditioning', hover_data=['furnishingstatus'])
fig.update_traces(marker_size = 5)#furnishing,basement, area has major effect on prices.

In [ ]:
house_df.price.corr(house_df.area)

0.5359973457780796

In [ ]:
house_df.price.corr(house_df.stories)

0.4207123661886163

In [ ]:
house_df.price.corr(house_df.parking)

0.3843936486357259

In [ ]:
categ_numeric = {'no':0, 'yes':1}
road_numeric = house_df.mainroad.map(categ_numeric)
house_df.price.corr(road_numeric)

0.2968984892639764

In [ ]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(house_df, test_size=0.2, random_state=42)

In [ ]:
train_inputs = train_set.drop('price', axis=1)
train_targets = train_set['price'].copy()
test_inputs = test_set.drop('price', axis=1)
test_targets = test_set['price'].copy()

In [ ]:
numeric_cols = train_inputs.select_dtypes(include=np.number).columns.tolist()
categorical_cols = train_inputs.select_dtypes(exclude=np.number).columns.tolist()

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
scaler.fit(train_inputs[numeric_cols])

StandardScaler()

In [ ]:
train_inputs[numeric_cols] = scaler.transform(train_inputs[numeric_cols])
test_inputs[numeric_cols] = scaler.transform(test_inputs[numeric_cols])

In [ ]:
train_inputs.describe()

               area      bedrooms     bathrooms       stories       parking
count  4.360000e+02  4.360000e+02  4.360000e+02  4.360000e+02  4.360000e+02
mean   1.222264e-16  1.629685e-16  7.333583e-17  6.926162e-17 -6.518741e-17
std    1.001149e+00  1.001149e+00  1.001149e+00  1.001149e+00  1.001149e+00
min   -1.591502e+00 -2.622298e+00 -5.579503e-01 -9.124989e-01 -8.030587e-01
25%   -7.058568e-01 -1.283514e+00 -5.579503e-01 -9.124989e-01 -8.030587e-01
50%   -2.970974e-01  5.527092e-02 -5.579503e-01  2.542152e-01 -8.030587e-01
75%    5.476719e-01  5.527092e-02  1.539173e+00  2.542152e-01  3.679566e-01
max    5.016775e+00  4.071624e+00  5.733420e+00  2.587644e+00  2.709987e+00

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [ ]:
encoder.fit(train_inputs[categorical_cols])

OneHotEncoder()

In [ ]:
encoded_cols = list(encoder.get_feature_names_out(categorical_cols))

In [ ]:
train_inputs[encoded_cols] = encoder.transform(train_set[categorical_cols]).toarray()
test_inputs[encoded_cols] = encoder.transform(test_set[categorical_cols]).toarray()

In [ ]:
train_inputs.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,...,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
46,0.384168,0.055271,1.539173,2.587644,yes,no,no,no,yes,0.367957,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
93,0.929181,0.055271,1.539173,-0.912499,yes,no,yes,no,yes,2.709987,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
335,-0.607755,-1.283514,-0.557950,-0.912499,yes,no,yes,no,yes,1.538972,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
412,-1.155492,0.055271,-0.557950,0.254215,yes,no,yes,no,no,-0.803059,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
471,-0.637730,0.055271,-0.557950,0.254215,yes,no,no,no,no,-0.803059,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [ ]:
train_inputs = train_inputs[numeric_cols + encoded_cols]
test_inputs = test_inputs[numeric_cols + encoded_cols]

# **Model_Creation_Training**

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(256, activation='relu', input_shape=(train_inputs.shape[1],)))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(1))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
              loss='mae',
              metrics=['mae'])

In [ ]:
history = model.fit(train_inputs, train_targets,
                    validation_split=0.2,
                    epochs=100,
                    batch_size=32)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 4358720.0000 - mae: 4358720.0000 - val_loss: 3473163.0000 - val_mae: 3473163.0000
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2896826.5000 - mae: 2896826.5000 - val_loss: 1252062.7500 - val_mae: 1252062.7500
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1371341.6250 - mae: 1371341.6250 - val_loss: 1035794.3750 - val_mae: 1035794.3750
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 923209.6250 - mae: 923209.6250 - val_loss: 863598.3750 - val_mae: 863598.3750
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 788763.1875 - mae: 788763.1875 - val_loss: 813833.2500 - val_mae: 813833.2500
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 819667.5000 - mae: 819667.5000 - val_loss: 822171.3750 - val_mae: 822171.3750
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 750105.8750 - mae: 750105.8750 - val_loss: 822038.7500 - val_mae: 822038.7500
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 694140.2500 - mae: 694140.2500 - val_loss: 822523.7500 - val_mae: 822523.7500
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 661940.5000 - mae: 661940.5000 - val_loss: 841219.6250 - val_mae: 841219.6250
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 704624.6250 - mae: 704624.6250 - val_loss: 829549.1875 - val_mae: 829549.1875
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 721523.1875 - mae: 721523.1875 - val_loss: 829521.6250 - val_mae: 829521.6250
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 708168.6250 - mae: 708168.6250 - val_loss: 829738.1875 - val_mae: 829738.1875
Epoch 13/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 680316.0000 - mae: 680316.0000 - val_loss: 834361.4375 - val_mae: 834361.4375
Epoch 14/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 748632.7500 - mae: 748632.7500 - val_loss: 840040.9375 - val_mae: 840040.9375
Epoch 15/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 694104.4375 - mae: 694104.4375 - val_loss: 824163.2500 - val_mae: 824163.2500
Epoch 16/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 688857.2500 - mae: 688857.2500 - val_loss: 834978.0000 - val_mae: 834978.0000
Epoch 17/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 719143.0625 - mae: 719143.0625 - val_loss: 836320.8125 - val_mae: 836320.8125
Epoch 18/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 679917.0000 - mae: 679917.0000 - val_loss: 845801.0000 - val_mae: 845801.0000
Epoch 19/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 685167.5000 - mae: 685167.5000 - val_loss: 825996.3750 - val_mae: 825996.3750
Epoch 20/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 674231.8750 - mae: 674231.8750 - val_loss: 827946.3750 - val_mae: 827946.3750
Epoch 21/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 702164.1250 - mae: 702164.1250 - val_loss: 826838.0625 - val_mae: 826838.0625
Epoch 22/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 637132.6250 - mae: 637132.6250 - val_loss: 831456.7500 - val_mae: 831456.7500
Epoch 23/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 658547.5000 - mae: 658547.5000 - val_loss: 833140.7500 - val_mae: 833140.7500
Epoch 24/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 635323.6250 - mae: 635323.6250 - val_loss: 835921.8125 - val_mae: 835921.8125
Epoch 25/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 681184.1875 - mae: 681184.1875 - val_loss: 833848.0000 - val_mae: 833848.0000
Epoch 26/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 680858.8750 - mae: 680858.8750 - val_loss: 855316.3750 - val_mae: 855316.3750
Epoch 27/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 739128.1250 - mae: 739128.1250 - val_loss: 847262.1875 - val_mae: 847262.1875
Epoch 28/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 698923.0000 - mae: 698923.0000 - val_loss: 839231.0625 - val_mae: 839231.0625
Epoch 29/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 664729.5625 - mae: 664729.5625 - val_loss: 827323.4375 - val_mae: 827323.4375
Epoch 30/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 713645.5000 - mae: 713645.5000 - val_loss: 835394.2500 - val_mae: 835394.2500
Epoch 31/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 699916.3125 - mae: 699916.3125 - val_loss: 830541.0625 - val_mae: 830541.0625
Epoch 32/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 651970.0000 - mae: 651970.0000 - val_loss: 830546.7500 - val_mae: 830546.7500
Epoch 33/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 649898.8750 - mae: 649898.8750 - val_loss: 839423.6250 - val_mae: 839423.6250
Epoch 34/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 679694.1875 - mae: 679694.1875 - val_loss: 840551.8125 - val_mae: 840551.8125
Epoch 35/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 638260.6875 - mae: 638260.6875 - val_loss: 838974.3750 - val_mae: 838974.3750
Epoch 36/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 673551.5625 - mae: 673551.5625 - val_loss: 837335.0000 - val_mae: 837335.0000
Epoch 37/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 696097.9375 - mae: 696097.9375 - val_loss: 831779.5625 - val_mae: 831779.5625
Epoch 38/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 715165.8750 - mae: 715165.8750 - val_loss: 826346.3750 - val_mae: 826346.3750
Epoch 39/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 674100.6250 - mae: 674100.6250 - val_loss: 833645.0625 - val_mae: 833645.0625
Epoch 40/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 652347.5000 - mae: 652347.5000 - val_loss: 831489.0625 - val_mae: 831489.0625
Epoch 41/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 690081.7500 - mae: 690081.7500 - val_loss: 849654.6250 - val_mae: 849654.6250
Epoch 42/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 706325.9375 - mae: 706325.9375 - val_loss: 834584.3750 - val_mae: 834584.3750
Epoch 43/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 707956.7500 - mae: 707956.7500 - val_loss: 830491.6250 - val_mae: 830491.6250
Epoch 44/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 673126.3125 - mae: 673126.3125 - val_loss: 830643.0625 - val_mae: 830643.0625
Epoch 45/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 719491.1250 - mae: 719491.1250 - val_loss: 854584.0000 - val_mae: 854584.0000
Epoch 46/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 692378.1250 - mae: 692378.1250 - val_loss: 825828.3750 - val_mae: 825828.3750
Epoch 47/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 637291.7500 - mae: 637291.7500 - val_loss: 847862.2500 - val_mae: 847862.2500
Epoch 48/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 709278.5625 - mae: 709278.5625 - val_loss: 834537.8125 - val_mae: 834537.8125
Epoch 49/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 701231.7500 - mae: 701231.7500 - val_loss: 852536.0000 - val_mae: 852536.0000
Epoch 50/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 695943.5000 - mae: 695943.5000 - val_loss: 830129.6250 - val_mae: 830129.6250
Epoch 51/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 679896.7500 - mae: 679896.7500 - val_loss: 834260.1875 - val_mae: 834260.1875
Epoch 52/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 730928.3125 - mae: 730928.3125 - val_loss: 869914.5625 - val_mae: 869914.5625
Epoch 53/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 736621.1875 - mae: 736621.1875 - val_loss: 838019.2500 - val_mae: 838019.2500
Epoch 54/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 650299.5000 - mae: 650299.5000 - val_loss: 845991.2500 - val_mae: 845991.2500
Epoch 55/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 648368.2500 - mae: 648368.2500 - val_loss: 838163.2500 - val_mae: 838163.2500
Epoch 56/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 751065.9375 - mae: 751065.9375 - val_loss: 833743.6250 - val_mae: 833743.6250
Epoch 57/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 647154.3125 - mae: 647154.3125 - val_loss: 851430.1875 - val_mae: 851430.1875
Epoch 58/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 753734.4375 - mae: 753734.4375 - val_loss: 830971.0000 - val_mae: 830971.0000
Epoch 59/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 662446.2500 - mae: 662446.2500 - val_loss: 840692.1875 - val_mae: 840692.1875
Epoch 60/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 680118.5625 - mae: 680118.5625 - val_loss: 862225.0000 - val_mae: 862225.0000
Epoch 61/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 735544.2500 - mae: 735544.2500 - val_loss: 834931.6250 - val_mae: 834931.6250
Epoch 62/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 627901.6250 - mae: 627901.6250 - val_loss: 835130.4375 - val_mae: 835130.4375
Epoch 63/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 657015.8125 - mae: 657015.8125 - val_loss: 837226.1875 - val_mae: 837226.1875
Epoch 64/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 683402.9375 - mae: 683402.9375 - val_loss: 838833.2500 - val_mae: 838833.2500
Epoch 65/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 762891.0000 - mae: 762891.0000 - val_loss: 874398.9375 - val_mae: 874398.9375
Epoch 66/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 787884.2500 - mae: 787884.2500 - val_loss: 854387.8125 - val_mae: 854387.8125
Epoch 67/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 691821.3750 - mae: 691821.3750 - val_loss: 893138.0625 - val_mae: 893138.0625
Epoch 68/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 809414.3125 - mae: 809414.3125 - val_loss: 852336.3750 - val_mae: 852336.3750
Epoch 69/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 663647.2500 - mae: 663647.2500 - val_loss: 838933.8125 - val_mae: 838933.8125
Epoch 70/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 686591.5000 - mae: 686591.5000 - val_loss: 843500.5625 - val_mae: 843500.5625
Epoch 71/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 708911.9375 - mae: 708911.9375 - val_loss: 841758.2500 - val_mae: 841758.2500
Epoch 72/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 693577.1875 - mae: 693577.1875 - val_loss: 838241.6250 - val_mae: 838241.6250
Epoch 73/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 669755.3750 - mae: 669755.3750 - val_loss: 836673.2500 - val_mae: 836673.2500
Epoch 74/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 682847.1875 - mae: 682847.1875 - val_loss: 841184.1875 - val_mae: 841184.1875
Epoch 75/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 668784.2500 - mae: 668784.2500 - val_loss: 841681.6250 - val_mae: 841681.6250
Epoch 76/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 699107.2500 - mae: 699107.2500 - val_loss: 836614.5625 - val_mae: 836614.5625
Epoch 77/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 732951.8125 - mae: 732951.8125 - val_loss: 836274.5625 - val_mae: 836274.5625
Epoch 78/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 669511.9375 - mae: 669511.9375 - val_loss: 831491.1875 - val_mae: 831491.1875
Epoch 79/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 668590.8750 - mae: 668590.8750 - val_loss: 843891.7500 - val_mae: 843891.7500
Epoch 80/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 729660.7500 - mae: 729660.7500 - val_loss: 825803.6250 - val_mae: 825803.6250
Epoch 81/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 666504.0000 - mae: 666504.0000 - val_loss: 831632.3750 - val_mae: 831632.3750
Epoch 82/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 727965.8750 - mae: 727965.8750 - val_loss: 865798.8125 - val_mae: 865798.8125
Epoch 83/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 695953.6875 - mae: 695953.6875 - val_loss: 837191.7500 - val_mae: 837191.7500
Epoch 84/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 662263.4375 - mae: 662263.4375 - val_loss: 841768.9375 - val_mae: 841768.9375
Epoch 85/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 701427.1875 - mae: 701427.1875 - val_loss: 843452.7500 - val_mae: 843452.7500
Epoch 86/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 672888.1250 - mae: 672888.1250 - val_loss: 867819.2500 - val_mae: 867819.2500
Epoch 87/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 727212.3125 - mae: 727212.3125 - val_loss: 829282.1875 - val_mae: 829282.1875
Epoch 88/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 670473.5625 - mae: 670473.5625 - val_loss: 860521.6250 - val_mae: 860521.6250
Epoch 89/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 689044.6250 - mae: 689044.6250 - val_loss: 825066.3750 - val_mae: 825066.3750
Epoch 90/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 742296.8125 - mae: 742296.8125 - val_loss: 838814.7500 - val_mae: 838814.7500
Epoch 91/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 680436.7500 - mae: 680436.7500 - val_loss: 832090.9375 - val_mae: 832090.9375
Epoch 92/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 642475.3125 - mae: 642475.3125 - val_loss: 837841.2500 - val_mae: 837841.2500
Epoch 93/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 687633.7500 - mae: 687633.7500 - val_loss: 857389.6250 - val_mae: 857389.6250
Epoch 94/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 696024.4375 - mae: 696024.4375 - val_loss: 838747.0625 - val_mae: 838747.0625
Epoch 95/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 658110.2500 - mae: 658110.2500 - val_loss: 835371.6250 - val_mae: 835371.6250
Epoch 96/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 690484.8125 - mae: 690484.8125 - val_loss: 827527.5625 - val_mae: 827527.5625
Epoch 97/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 734350.3750 - mae: 734350.3750 - val_loss: 820243.1875 - val_mae: 820243.1875
Epoch 98/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 655507.0625 - mae: 655507.0625 - val_loss: 837784.8125 - val_mae: 837784.8125
Epoch 99/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 658199.9375 - mae: 658199.9375 - val_loss: 835934.0000 - val_mae: 835934.0000
Epoch 100/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 648928.9375 - mae: 648928.9375 - val_loss: 832650.7500 - val_mae: 832650.7500

In [ ]:
model.evaluate(test_inputs, test_targets)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 963869.9375 - mae: 963870.4375

[1007154.5625, 1007155.0625]